server:
  port: 8081
  servlet:
    context-path: /device

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/device"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update

app:
  services:
    identity: http://localhost:8080/identity